# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=main.models.image_path),
        ),
    ]
